from ..schemas import DestinationPublic

# Curated static catalogue; facts are descriptive and budgets are clearly labelled estimates.
DESTINATIONS = [
    DestinationPublic(id="goa", name="Goa", state="Goa", short_description="Arabian Sea beaches, Portuguese-era architecture, and coastal cuisine.", description="Explore Goa's palm-lined coastline, historic churches and forts, and lively local markets. North and South Goa offer different paces, from busy beach towns to quieter stretches of coast.", category="Beach", image="https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=85", latitude=15.2993, longitude=74.1240, best_time_to_visit="November to February", estimated_budget="₹2,500–₹6,000 per person/day (estimate)", tags=["coast", "beaches", "heritage"]),
    DestinationPublic(id="varkala", name="Varkala", state="Kerala", short_description="A cliffside coastal town overlooking the Arabian Sea.", description="Varkala is known for the red laterite cliffs beside Papanasam Beach and its coastal walking paths. Respect local swimming and cliff safety advisories.", category="Beach", image="https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=85", latitude=8.7379, longitude=76.7163, best_time_to_visit="October to March", estimated_budget="₹2,000–₹5,000 per person/day (estimate)", tags=["cliffs", "coast", "sunset"]),
    DestinationPublic(id="puri", name="Puri", state="Odisha", short_description="A Bay of Bengal beach city and an important pilgrimage destination.", description="Puri combines a long coastline with the historic Jagannath Temple and access to the bird-rich Chilika lagoon region. Temple access rules apply to visitors.", category="Spiritual", image="https://images.unsplash.com/photo-1590123732197-e7079d4ea7e1?auto=format&fit=crop&w=1200&q=85", latitude=19.8135, longitude=85.8312, best_time_to_visit="October to February", estimated_budget="₹1,800–₹4,500 per person/day (estimate)", tags=["pilgrimage", "coast", "culture"]),
    DestinationPublic(id="manali", name="Manali", state="Himachal Pradesh", short_description="A Himalayan town set beside the Beas River.", description="Manali is a base for mountain scenery, local markets, temples, and routes toward the Kullu valley. High mountain roads and activities can be seasonal; check local conditions before travel.", category="Mountain", image="https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=85", latitude=32.2432, longitude=77.1892, best_time_to_visit="March to June; December to February for snow (conditions vary)", estimated_budget="₹2,500–₹6,500 per person/day (estimate)", tags=["Himalaya", "river", "outdoors"]),
    DestinationPublic(id="gulmarg", name="Gulmarg", state="Jammu and Kashmir", short_description="A mountain resort town in the Pir Panjal range.", description="Gulmarg is known for alpine meadows and seasonal snow sports. Weather and gondola operations can change quickly, so confirm local operating conditions before setting out.", category="Adventure", image="https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=85", latitude=34.0484, longitude=74.3805, best_time_to_visit="May to October for meadows; December to March for snow (conditions vary)", estimated_budget="₹3,000–₹8,000 per person/day (estimate)", tags=["snow", "mountains", "skiing"]),
    DestinationPublic(id="darjeeling", name="Darjeeling", state="West Bengal", short_description="A Himalayan hill town known for tea gardens and mountain views.", description="Darjeeling offers heritage railway journeys, tea estates, and views toward the eastern Himalaya on clear days. The Darjeeling Himalayan Railway is a UNESCO-listed mountain railway.", category="Mountain", image="https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85", latitude=27.0410, longitude=88.2663, best_time_to_visit="March to May and October to November", estimated_budget="₹2,500–₹6,000 per person/day (estimate)", tags=["tea", "railway", "Himalaya"]),
    DestinationPublic(id="jaipur", name="Jaipur", state="Rajasthan", short_description="Rajasthan's capital, with historic forts, palaces, and bazaars.", description="Jaipur's historic walled city and monuments reflect the planned city founded by Sawai Jai Singh II. Visit Amber Fort, City Palace, and local markets while checking each site's current hours.", category="Heritage", image="https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=85", latitude=26.9124, longitude=75.7873, best_time_to_visit="October to March", estimated_budget="₹2,000–₹5,500 per person/day (estimate)", tags=["forts", "architecture", "markets"]),
    DestinationPublic(id="agra", name="Agra", state="Uttar Pradesh", short_description="Home to the Taj Mahal and other Mughal-era monuments.", description="Agra is a major heritage destination on the Yamuna River. The Taj Mahal and Agra Fort are UNESCO World Heritage Sites; check official visitor guidance and opening schedules before visiting.", category="Heritage", image="https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=85", latitude=27.1767, longitude=78.0081, best_time_to_visit="October to March", estimated_budget="₹2,000–₹5,500 per person/day (estimate)", tags=["UNESCO", "Mughal", "architecture"]),
    DestinationPublic(id="hampi", name="Hampi", state="Karnataka", short_description="A landscape of Vijayanagara-era ruins among granite hills.", description="The Hampi Group of Monuments preserves remains of the Vijayanagara Empire across a broad landscape of temples, bazaars, and stone formations. Many sites are outdoors and have limited shade.", category="Heritage", image="https://images.unsplash.com/photo-1600100397608-f010a1f26e8a?auto=format&fit=crop&w=1200&q=85", latitude=15.3350, longitude=76.4600, best_time_to_visit="October to February", estimated_budget="₹1,800–₹4,500 per person/day (estimate)", tags=["UNESCO", "ruins", "architecture"]),
    DestinationPublic(id="kaziranga", name="Kaziranga National Park", state="Assam", short_description="A protected floodplain landscape in the Brahmaputra valley.", description="Kaziranga National Park is a UNESCO World Heritage Site recognised for its biodiversity and one-horned rhinoceros conservation. Park access is seasonal and regulated; follow official park and wildlife guidance.", category="Nature", image="https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1200&q=85", latitude=26.5775, longitude=93.1711, best_time_to_visit="November to April (park access is seasonal)", estimated_budget="₹3,000–₹8,000 per person/day (estimate)", tags=["wildlife", "UNESCO", "conservation"]),
    DestinationPublic(id="alleppey", name="Alappuzha Backwaters", state="Kerala", short_description="A network of lagoons, canals, and waterways along Kerala's coast.", description="Alappuzha is a gateway to Kerala's backwater landscape, where waterways connect villages, paddy fields, and the coast. Use licensed operators and follow local water-safety advice.", category="Nature", image="https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=85", latitude=9.4981, longitude=76.3388, best_time_to_visit="October to March", estimated_budget="₹2,500–₹7,000 per person/day (estimate)", tags=["backwaters", "waterways", "houseboats"]),
    DestinationPublic(id="varanasi", name="Varanasi", state="Uttar Pradesh", short_description="A historic city on the Ganges with riverfront ghats and temples.", description="Varanasi is one of India's oldest continuously inhabited cities and an important centre of pilgrimage and learning. Be mindful of river conditions and local customs at religious sites.", category="Spiritual", image="https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=85", latitude=25.3176, longitude=82.9739, best_time_to_visit="October to March", estimated_budget="₹1,800–₹5,000 per person/day (estimate)", tags=["Ganges", "ghats", "culture"]),
    DestinationPublic(id="rishikesh", name="Rishikesh", state="Uttarakhand", short_description="A Ganges-side town at the foothills of the Himalaya.", description="Rishikesh is known for its river setting, yoga centres, and access to outdoor activities. River activities depend on season and local conditions; use qualified operators.", category="Adventure", image="https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=85", latitude=30.0869, longitude=78.2676, best_time_to_visit="September to November and February to May", estimated_budget="₹2,000–₹5,500 per person/day (estimate)", tags=["Ganges", "yoga", "outdoors"]),
    DestinationPublic(id="mumbai", name="Mumbai", state="Maharashtra", short_description="India's coastal financial capital, with historic districts and markets.", description="Mumbai brings together a busy harbour, colonial-era landmarks, museums, markets, and a diverse food scene. Local trains and ferries provide useful ways to move around the city.", category="City", image="https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=85", latitude=19.0760, longitude=72.8777, best_time_to_visit="November to February", estimated_budget="₹3,000–₹8,000 per person/day (estimate)", tags=["coast", "architecture", "food"]),
    DestinationPublic(id="kochi", name="Kochi", state="Kerala", short_description="A port city shaped by centuries of maritime exchange.", description="Kochi's historic Fort Kochi district, waterfront, and ferry-linked neighbourhoods reflect its long trading history. The city is a convenient starting point for exploring central Kerala.", category="City", image="https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=85", latitude=9.9312, longitude=76.2673, best_time_to_visit="October to March", estimated_budget="₹2,500–₹6,000 per person/day (estimate)", tags=["port", "heritage", "food"]),
]

DESTINATIONS_BY_ID = {destination.id: destination for destination in DESTINATIONS}
CATEGORIES = sorted({destination.category for destination in DESTINATIONS})
STATES = sorted({destination.state for destination in DESTINATIONS})


def list_destinations(search: str | None = None, category: str | None = None, state: str | None = None):
    items = DESTINATIONS
    term = (search or "").strip().casefold()
    if term:
        items = [
            destination for destination in items
            if term in " ".join((destination.name, destination.state, destination.category,
                                 destination.short_description, *destination.tags)).casefold()
        ]
    if category:
        items = [item for item in items if item.category.casefold() == category.casefold()]
    if state:
        items = [item for item in items if item.state.casefold() == state.casefold()]
    return items


def get_destination(destination_id: str):
    return DESTINATIONS_BY_ID.get(destination_id.casefold())
