import React, { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FaPlus, FaSuitcaseRolling } from "react-icons/fa";
import PageContainer from "../components/PageContainer";
import Card from "../components/Card";
import Button from "../components/Button";
import EmptyState from "../components/EmptyState";
import { deleteTrip, getTrips } from "../services/tripService";

function ConfirmDialog({ trip, busy, error, onClose, onConfirm }) {
  if (!trip) return null;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-sm" role="presentation"><section role="alertdialog" aria-modal="true" aria-labelledby="delete-title" className="w-full max-w-md rounded-2xl border border-white/15 bg-slate-900 p-6 shadow-2xl"><h2 id="delete-title" className="text-xl font-bold text-white">Delete this trip?</h2><p className="mt-2 text-sm text-slate-300">“{trip.title}” and its itinerary will be permanently removed.</p>{error && <p role="alert" className="mt-3 text-sm text-rose-200">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose} disabled={busy}>Keep trip</Button><Button variant="danger" onClick={onConfirm} loading={busy}>Delete trip</Button></div></section></div>;
}

export default function Trips() {
  const navigate = useNavigate();
  const [trips, setTrips] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
  const [deleting, setDeleting] = useState(null); const [busy, setBusy] = useState(false); const [deleteError, setDeleteError] = useState("");
  const load = useCallback(() => { let active = true; setLoading(true); setError(""); getTrips().then((items) => { if (active) setTrips(items); }).catch((e) => { if (active) setError(e.response?.data?.detail || "Your trips could not be loaded."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  useEffect(() => load(), [load, attempt]);
  const remove = async () => { setBusy(true); setDeleteError(""); try { await deleteTrip(deleting.id); setTrips((all) => all.filter((trip) => trip.id !== deleting.id)); setDeleting(null); } catch (e) { setDeleteError(e.response?.data?.detail || "This trip could not be deleted."); } finally { setBusy(false); } };
  const now = new Date();
  const categorised = { Upcoming: trips.filter((trip) => trip.start_date && new Date(`${trip.start_date}T00:00:00`) >= new Date(now.toDateString())), Saved: trips.filter((trip) => !trip.start_date), Past: trips.filter((trip) => trip.start_date && new Date(`${trip.start_date}T00:00:00`) < new Date(now.toDateString())) };
  return <PageContainer title="Your journeys" badge="MY TRIPS" subtitle="Return to a saved plan, update your preferences, or start somewhere new." action={<Button as={Link} to="/planner" icon={<FaPlus/>}>Plan a trip</Button>}>
    {loading ? <div role="status" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((n) => <div key={n} className="h-48 animate-pulse rounded-2xl border border-white/10 bg-slate-900/70" />)}</div> : error ? <Card variant="darkGlass" hoverable={false} className="text-center"><p role="alert" className="text-rose-100">{error}</p><Button className="mt-4" variant="secondary" onClick={() => setAttempt((n) => n+1)}>Try again</Button></Card> : !trips.length ? <EmptyState icon={<FaSuitcaseRolling/>} title="Your next journey starts here" description="Saved itineraries appear here so you can pick up planning whenever you’re ready." actionText="Plan a trip" onAction={() => navigate("/planner")} /> : <div className="space-y-8">{Object.entries(categorised).filter(([, items]) => items.length).map(([category, items]) => <section key={category}><h2 className="mb-4 text-xl font-bold text-white">{category}<span className="ml-2 text-sm font-medium text-slate-400">{items.length}</span></h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((trip) => <Card key={trip.id} variant="darkGlass" hoverable={false} className="flex flex-col overflow-hidden !p-0"><div className="relative h-36 bg-slate-800"><img src={trip.destination.image || ""} alt="" className="h-full w-full object-cover opacity-75"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 to-transparent"/><span className="absolute bottom-3 left-4 text-xs font-semibold uppercase tracking-wider text-amber-200">{trip.destination.state}</span></div><div className="flex flex-1 flex-col p-5"><h3 className="text-lg font-bold text-white">{trip.title}</h3><p className="mt-1 text-sm text-slate-300">{trip.destination.name} · {trip.duration_days} days</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-300"><span className="rounded-full border border-white/10 px-2.5 py-1 capitalize">{trip.travel_style}</span><span className="rounded-full border border-white/10 px-2.5 py-1">₹{trip.budget_inr.toLocaleString("en-IN")}</span>{trip.start_date && <span className="rounded-full border border-white/10 px-2.5 py-1">{new Date(`${trip.start_date}T00:00:00`).toLocaleDateString("en-IN")}</span>}</div>{trip.itinerary_stale && <p className="mt-3 text-xs text-amber-200">Preferences changed · refresh itinerary</p>}<div className="mt-auto flex gap-2 pt-5"><Button as={Link} to={`/trips/${trip.id}`} variant="primary" className="flex-1">Open trip</Button><Button aria-label={`Delete ${trip.title}`} variant="ghost" onClick={() => { setDeleting(trip); setDeleteError(""); }}>Delete</Button></div></div></Card>)}</div></section>)}</div>}
    <ConfirmDialog trip={deleting} busy={busy} error={deleteError} onClose={() => setDeleting(null)} onConfirm={remove}/>
  </PageContainer>;
}
